name: Shadow-Xtech-V1 
services:
  - name: Shadow-Ai
    type: web
    ports:
      - 5000
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    regions:
      - fra
      - sin
      
